spring:
  profiles:
    active: dev
  application:
    name: loan-file-service

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 106.14.203.23:22122
#  pool:
#    #从池中借出的对象的最大数目
#    max-total: 153
#    #获取连接时的最大等待毫秒数100
#     max-wait-millis: 102